branch-defaults:
  main:
    environment: Backend-glyphic-ai-env-2
environment-defaults:
  Backend-glyphic-ai-env-2:
    branch: null
    repository: null
global:
  application_name: backend-glyphic-ai
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
packages:
  yum:
    gcc: []
    gcc-c++: []
    python-devel: []